# Generated by Django 3.2.4 on 2023-10-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20231002_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
