# Generated by Django 3.2.4 on 2023-10-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20231002_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='course',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='year',
            field=models.TextField(null=True),
        ),
    ]
