# Generated by Django 3.2.4 on 2023-10-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20231002_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='apply',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
