# Generated by Django 3.2.4 on 2023-10-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_signup_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('contact', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
