# Generated by Django 3.2.4 on 2023-10-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('picture', models.ImageField(null=True, upload_to='abc')),
                ('college', models.TextField(null=True)),
                ('feedback', models.TextField(null=True)),
            ],
        ),
    ]
