# Generated by Django 3.2.4 on 2023-10-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/abc/'),
        ),
    ]
