# Generated by Django 3.2.4 on 2023-10-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_imagegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='vediogallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlink', models.CharField(max_length=500, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
