# Generated by Django 3.2.4 on 2023-10-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_vediogallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vediogallery',
            new_name='videogallery',
        ),
    ]
