# Generated by Django 3.2.4 on 2023-10-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_vediogallery_videogallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogallery',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.category'),
        ),
    ]
