# Generated by Django 3.2.4 on 2023-10-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_videogallery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogallery',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category'),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='vlink',
            field=models.ImageField(null=True, upload_to='static/video/'),
        ),
    ]
