# Generated by Django 3.2.4 on 2023-10-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20231004_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogallery',
            name='vlink',
            field=models.TextField(null=True),
        ),
    ]
