# Generated by Django 3.2.4 on 2023-10-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_placements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placements',
            old_name='year',
            new_name='fyear',
        ),
        migrations.AddField(
            model_name='placements',
            name='syear',
            field=models.IntegerField(null=True),
        ),
    ]
