# Generated by Django 3.2.4 on 2023-10-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20231004_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='placements',
            name='company',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
