# Generated by Django 3.2.4 on 2023-10-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursecategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='courses',
            name='cname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
