# Generated by Django 3.2.4 on 2023-10-06 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_courses_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(null=True)),
                ('coursecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.coursecategory')),
            ],
        ),
    ]
