# Generated by Django 3.2.4 on 2023-10-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='language',
        ),
    ]
