# Generated by Django 3.2.4 on 2023-10-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_delete_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='enroll',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
