# Generated by Django 3.2.4 on 2023-10-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_signup_enroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
